# permissions for end users to view mongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongo-operator
    app.kubernetes.io/part-of: mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongo-viewer-role
rules:
- apiGroups:
  - api.my.domain
  resources:
  - mongoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.my.domain
  resources:
  - mongoes/status
  verbs:
  - get
