apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: flows
type: Opaque
stringData:
  username: "username"  # Replace with your Base64-encoded username
  password: "password"  # Replace with your Base64-encoded password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-prod
  namespace: flows
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-prod-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
